#ifndef KELLY_DECOMP_FE_MENU_ENTRY_DISABLE_SHARED_H
#define KELLY_DECOMP_FE_MENU_ENTRY_DISABLE_SHARED_H

#include "KS/SRC/ks/FEPanel.h"

#define KELLY_DECOMP_FULL_FEMENU_ENTRY
#include "KS/SRC/ks/FEMenu_shared.h"
#undef KELLY_DECOMP_FULL_FEMENU_ENTRY

#pragma interface

#endif
