#ifndef KELLY_DECOMP_GAME_MODE_SHARED_H
#define KELLY_DECOMP_GAME_MODE_SHARED_H

enum game_mode_t {
    GAME_MODE_CAREER,
    GAME_MODE_FREESURF_INFINITE,
    GAME_MODE_FREESURF_HIGHSCORE,
    GAME_MODE_FREESURF_ICON,
    GAME_MODE_PRACTICE,
    GAME_MODE_TIME_ATTACK,
    GAME_MODE_METER_ATTACK,
    GAME_MODE_SEA_HORSE,
    GAME_MODE_HEAD_TO_HEAD,
    GAME_MODE_PUSH
};

#endif
