#!/usr/bin/env python3

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path, PurePosixPath


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "src"
GENERATED_SOURCE_ROOT = ROOT / "build" / "src_functions"
SOURCE_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hh",
    ".hpp",
    ".hxx",
}
MARKER_RE = re.compile(
    r"^#if defined\(KELLY_DECOMP_FUNCTION_([0-9A-F]{8})\)$",
    re.MULTILINE,
)
ADDRESS_MARKER_RE = re.compile(
    r"^// 0x([0-9A-Fa-f]{8})\s+.+$",
    re.MULTILINE,
)
EMPTY_COMPILER_BARRIER_RE = re.compile(
    r'__asm__\s+volatile\s*\(\s*""\s*\)'
)
INLINE_ASM_TEMPLATE_RE = re.compile(
    r"(?:__asm__|asm)\s+(?:volatile|__volatile__)\s*"
    r'\(\s*((?:"(?:\\.|[^"\\])*"\s*)+)',
    re.DOTALL,
)
STRING_LITERAL_RE = re.compile(r'"((?:\\.|[^"\\])*)"', re.DOTALL)
SYMBOL_ONLY_ASM_LINE_RE = re.compile(
    r"(?:\.globl\s+[A-Za-z0-9_.$]+|[A-Za-z0-9_.$]+:)$"
)
LOCAL_INCLUDE_RE = re.compile(
    r'^\s*#include\s+"([^"]+)"',
    re.MULTILINE,
)

# Any new instruction-emitting inline assembly requires an explicit source
# review and a code change here. Full-function assembly replacements are never
# permitted; these entries cover released inline assembly or previously
# reviewed, narrowly scoped scheduling/conversion annotations.
REVIEWED_INSTRUCTION_ASM = {
    0x0010F030: "documented generated 8-byte fill loop schedule",
    0x0010FA58: "documented generated 8-byte fill loop schedule",
    0x00110C28: "documented generated pointer fill loop schedule",
    0x00111AA0: "documented generated pointer fill loop schedule",
    0x00111FD0: "documented generated pointer fill loop schedule",
    0x001185C8: "documented floating-point scheduling nop",
    0x0011ECE0: "documented generated pointer fill loop schedule",
    0x0011FF50: "documented generated ushort fill loop schedule",
    0x00142300: "documented generated pointer fill loop schedule",
    0x00139DB0: "documented FPU hazard and independent-store schedule",
    0x0014C918: "documented integer-to-float conversion sequence",
    0x001556D8: "documented list-traversal scheduling nop",
    0x001D9B00: "documented aggregate color load/store schedule",
    0x001E3340: "released FTOI conversion inline assembly",
    0x001EAD68: "documented list-traversal scheduling nop",
    0x001F9B18: "documented floating-point scheduling nop",
    0x00229F68: "documented filter-loop scheduling nop",
    0x002510F8: "documented floating-point comparison nop",
    0x00286678: "documented generated two-player combat loop schedule",
    0x002AE0F0: "documented generated pointer fill loop schedule",
    0x002AF8C0: "documented generated pointer fill loop schedule",
    0x002AFE70: "documented generated pointer fill loop schedule",
    0x002B0B58: "documented generated pointer fill loop schedule",
    0x002B0E80: "documented generated pointer fill loop schedule",
    0x002B11A8: "documented generated pointer fill loop schedule",
    0x002B14D0: "documented generated pointer fill loop schedule",
    0x002B17F8: "documented generated pointer fill loop schedule",
    0x002B1B20: "documented generated pointer fill loop schedule",
    0x002B1E48: "documented generated pointer fill loop schedule",
    0x002B22F8: "documented generated pointer fill loop schedule",
    0x002B8490: "documented floating-point comparison nop",
    0x002FBB48: "documented generated-loop scheduling nop",
    0x002F09E0: "documented generated pointer fill loop schedule",
    0x002F43C8: "documented generated 8-byte fill loop schedule",
    0x002F5E60: "documented generated pointer fill loop schedule",
    0x002FA938: "documented generated integer fill loop schedule",
    0x002FAE20: "documented generated byte fill loop schedule",
    0x002FB9E0: "documented generated pointer fill loop schedule",
    0x00340510: "documented integer-to-float conversion sequence",
    0x00340540: "documented integer-to-float conversion sequence",
    0x00387818: "documented thread-loop scheduling nops",
    0x00391718: "released VU unit-matrix inline assembly",
    0x00391808: "released inlined VU matrix-apply sequence",
    0x00396D90: "released ExitHandler instruction expansion",
    0x00397540: "released nglFTOI conversion sequence",
    0x0039A0B8: "documented list-traversal scheduling nop",
}

IMPLEMENTATION_OVERRIDES = {
    "KS/SRC/AIController.h": "KS/SRC/AIController_methods.cpp",
    "KS/SRC/ai_actions.h": "KS/SRC/ai_actions_methods.cpp",
    "KS/SRC/ai_goals.h": "KS/SRC/ai_goals_methods.cpp",
    "KS/SRC/ai_locomotion.h": "KS/SRC/ai_locomotion_methods.cpp",
    "KS/SRC/anim.h": "KS/SRC/anim_methods.cpp",
    "KS/SRC/anim_maker.h": "KS/SRC/anim_maker_methods.cpp",
    "KS/SRC/animation_interface.h": "KS/SRC/animation_interface_rtti.cpp",
    "KS/SRC/ai_interface.h": "KS/SRC/ai_interface_rtti.cpp",
    "KS/SRC/beam.h": "KS/SRC/beam_methods.cpp",
    "KS/SRC/ks/BoardFrontEnd.h": "KS/SRC/ks/BoardFrontEnd_methods.cpp",
    "KS/SRC/bone.h": "KS/SRC/bone.cpp",
    "KS/SRC/capsule.h": "KS/SRC/capsule_methods.cpp",
    "KS/SRC/camera.h": "KS/SRC/camera_methods.cpp",
    "KS/SRC/conglom.h": "KS/SRC/conglom_methods.cpp",
    "KS/SRC/entity.h": "KS/SRC/entity_methods.cpp",
    "KS/SRC/element.h": "KS/SRC/element_methods.cpp",
    "KS/SRC/entity_anim.h": "KS/SRC/entity_anim_methods.cpp",
    "KS/SRC/ks/eventmanager.h": "KS/SRC/ks/eventmanager_rtti.cpp",
    "KS/SRC/entity_interface.h": "KS/SRC/entity_interface.cpp",
    "KS/SRC/ks/ExtrasFrontEnd.h":
        "KS/SRC/ks/ExtrasFrontEnd_methods.cpp",
    "KS/SRC/ks/FEPanel.h": "KS/SRC/ks/FEPanel_methods.cpp",
    "KS/SRC/ks/FEMenu.h": "KS/SRC/ks/FEMenu_methods.cpp",
    "KS/SRC/ks/FrontEndMenus.h": "KS/SRC/ks/FrontEndMenus_methods.cpp",
    "KS/SRC/ks/FrontEndManager.h": "KS/SRC/ks/FrontEndManager_rtti.cpp",
    "KS/SRC/ks/GraphicalMenuSystem.h":
        "KS/SRC/ks/GraphicalMenuSystem_methods.cpp",
    "KS/SRC/graph.h": "KS/SRC/graph_methods.cpp",
    "KS/SRC/HWOSPS2/ps2_input.h":
        "KS/SRC/HWOSPS2/ps2_input_methods.cpp",
    "KS/SRC/ks/CheatFrontEnd.h": "KS/SRC/ks/CheatFrontEnd_methods.cpp",
    "KS/SRC/ks/career.h": "KS/SRC/ks/career.cpp",
    "KS/SRC/ks/SaveLoadFrontEnd.h":
        "KS/SRC/ks/SaveLoadFrontEnd_methods.cpp",
    "KS/SRC/ks/ks_camera.h": "KS/SRC/ks/ks_camera_methods.cpp",
    "KS/SRC/ks/ksdbmenu.h": "KS/SRC/ks/ksdbmenu_methods.cpp",
    "KS/SRC/ks/ksreplay.h": "KS/SRC/ks/ksreplay_methods.cpp",
    "KS/SRC/ks/LogbookFrontEnd.h":
        "KS/SRC/ks/LogbookFrontEnd_rtti.cpp",
    "KS/SRC/ks/MainFrontEnd.h": "KS/SRC/ks/MainFrontEnd_methods.cpp",
    "KS/SRC/ks/MCDetectFrontEnd.h": "KS/SRC/ks/MCDetectFrontEnd_rtti.cpp",
    "KS/SRC/ks/kellyslater_controller.h":
        "KS/SRC/ks/kellyslater_controller_methods.cpp",
    "KS/SRC/ks/menu.h": "KS/SRC/ks/menu_methods.cpp",
    "KS/SRC/ks/menu_scoring.h": "KS/SRC/ks/menu_scoring_methods.cpp",
    "KS/SRC/ks/menusys.h": "KS/SRC/ks/menusys_rtti.cpp",
    "KS/SRC/ks/trail.h": "KS/SRC/ks/trail_rtti.cpp",
    "KS/SRC/ks/TutorialFrontEnd.h":
        "KS/SRC/ks/TutorialFrontEnd_rtti.cpp",
    "KS/SRC/ks/TrickBookFrontEnd.h":
        "KS/SRC/ks/TrickBookFrontEnd_methods.cpp",
    "KS/SRC/ks/wave.h": "KS/SRC/ks/wave_methods.cpp",
    "KS/SRC/vm_thread.h": "KS/SRC/vm_thread_methods.cpp",
    "KS/SRC/ks/dxt1_codebook.h": "KS/SRC/ks/dxt1_codebook_rtti.cpp",
    "KS/SRC/ks/floatobj.h": "KS/SRC/ks/floatobj_methods.cpp",
    "KS/SRC/ks/igo_widget.h": "KS/SRC/ks/igo_widget_rtti.cpp",
    "KS/SRC/ks/igo_widget_grid.h": "KS/SRC/ks/igo_widget_grid_methods.cpp",
    "KS/SRC/light.h": "KS/SRC/light_methods.cpp",
    "KS/SRC/lightmgr.h": "KS/SRC/lightmgr_methods.cpp",
    "KS/SRC/linear_anim.h": "KS/SRC/linear_anim_rtti.cpp",
    "KS/SRC/marker.h": "KS/SRC/marker_methods.cpp",
    "KS/SRC/mobject.h": "KS/SRC/mobject_methods.cpp",
    "KS/SRC/mcs.h": "KS/SRC/mcs_methods.cpp",
    "KS/SRC/matfac.h": "KS/SRC/matfac_rtti.cpp",
    "KS/SRC/hard_attrib_interface.h": "KS/SRC/hard_attrib_interface.cpp",
    "KS/SRC/inputmgr.h": "KS/SRC/inputmgr_methods.cpp",
    "KS/SRC/interface.h": "KS/SRC/interface_methods.cpp",
    "KS/SRC/item.h": "KS/SRC/item_methods.cpp",
    "KS/SRC/link_interface.h": "KS/SRC/link_interface.cpp",
    "KS/SRC/owner_interface.h": "KS/SRC/owner_interface.cpp",
    "KS/SRC/physical_interface.h": "KS/SRC/physical_interface.cpp",
    "KS/SRC/pmesh.h": "KS/SRC/pmesh_methods.cpp",
    "KS/SRC/particle.h": "KS/SRC/particle_methods.cpp",
    "KS/SRC/path.h": "KS/SRC/path_methods.cpp",
    "KS/SRC/polytube.h": "KS/SRC/polytube_methods.cpp",
    "KS/SRC/po_anim.h": "KS/SRC/po_anim_rtti.cpp",
    "KS/SRC/render_interface.h": "KS/SRC/render_interface.cpp",
    "KS/SRC/skeleton_interface.h": "KS/SRC/skeleton_interface.cpp",
    "KS/SRC/singleton.h": "KS/SRC/singleton.cpp",
    "KS/SRC/signals.h": "KS/SRC/signals.cpp",
    "KS/SRC/signal_anim.h": "KS/SRC/signal_anim_rtti.cpp",
    "KS/SRC/script_data_interface.h": "KS/SRC/script_data_interface.cpp",
    "KS/SRC/script_library_class.h": "KS/SRC/script_library_class_methods.cpp",
    "KS/SRC/script_lib_trigger.h": "KS/SRC/script_lib_trigger_methods.cpp",
    "KS/SRC/script_lib_beam.h": "KS/SRC/script_lib_beam_methods.cpp",
    "KS/SRC/script_lib_anim.h": "KS/SRC/script_lib_anim_methods.cpp",
    "KS/SRC/slave_interface.h": "KS/SRC/slave_interface.cpp",
    "KS/SRC/soft_attrib_interface.h": "KS/SRC/soft_attrib_interface.cpp",
    "KS/SRC/stringx.h": "KS/SRC/stringx_methods.cpp",
    "KS/SRC/time_interface.h": "KS/SRC/time_interface.cpp",
    "KS/SRC/trigger.h": "KS/SRC/trigger_methods.cpp",
    "KS/SRC/visrep.h": "KS/SRC/visrep_rtti.cpp",
    "KS/SRC/widget.h": "KS/SRC/widget_methods.cpp",
}


@dataclass(frozen=True)
class FunctionSource:
    address: int
    path: Path
    merged: bool
    guarded: bool = True


def selector_macro(address: int) -> str:
    return f"KELLY_DECOMP_FUNCTION_{address:08X}"


def uses_matching_compiler_barrier(source: str) -> bool:
    return (
        EMPTY_COMPILER_BARRIER_RE.search(source) is not None
        or "KELLY_DECOMP_COMPILER_BARRIER()" in source
    )


def uses_instruction_emitting_inline_asm(source: str) -> bool:
    for match in INLINE_ASM_TEMPLATE_RE.finditer(source):
        template = "".join(STRING_LITERAL_RE.findall(match.group(1)))
        lines = template.replace(r"\n", "\n").replace(r"\t", "\t").splitlines()
        if any(
            line and SYMBOL_ONLY_ASM_LINE_RE.fullmatch(line) is None
            for line in (line.strip() for line in lines)
        ):
            return True
    return False


def uses_released_instruction_asm(address: int, source: str) -> bool:
    reason = REVIEWED_INSTRUCTION_ASM.get(address, "")
    return (
        reason.startswith("released ")
        and uses_instruction_emitting_inline_asm(source)
    )


def validate_instruction_asm(address: int, source: str) -> None:
    if ".set noreorder" in source:
        raise RuntimeError(
            f"0x{address:08X} uses forbidden `.set noreorder` inline "
            "assembly; defer the function instead of replacing its body"
        )
    if (
        uses_instruction_emitting_inline_asm(source)
        and address not in REVIEWED_INSTRUCTION_ASM
    ):
        raise RuntimeError(
            f"0x{address:08X} uses unreviewed instruction-emitting inline "
            "assembly; source-level candidates must be deferred when they "
            "do not match"
        )


def normalize_matching_annotations(source: str) -> str:
    return EMPTY_COMPILER_BARRIER_RE.sub(
        "KELLY_DECOMP_COMPILER_BARRIER()",
        source,
    )


def resolve_local_include(path: Path, include: str) -> Path | None:
    candidates = (
        path.parent / include,
        ROOT / "include" / include,
        SOURCE_ROOT / include,
    )
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    return None


def hash_local_include(
    path: Path,
    digest: object,
    seen: set[Path],
) -> None:
    path = path.resolve()
    if path in seen:
        return
    seen.add(path)

    text = path.read_text(encoding="utf-8")
    digest.update(path.relative_to(ROOT).as_posix().encode())
    digest.update(b"\0")
    digest.update(text.encode())
    digest.update(b"\0")
    for include in LOCAL_INCLUDE_RE.findall(text):
        dependency = resolve_local_include(path, include)
        if dependency is not None:
            hash_local_include(dependency, digest, seen)


def shared_context_digest(path: Path, text: str) -> str:
    guarded_marker = MARKER_RE.search(text)
    address_marker = ADDRESS_MARKER_RE.search(text)
    markers = [
        marker
        for marker in (guarded_marker, address_marker)
        if marker is not None
    ]
    marker = min(markers, key=lambda match: match.start()) if markers else None
    preamble = text[: marker.start()] if marker is not None else text
    digest = hashlib.sha1()
    digest.update(preamble.encode())
    for include in LOCAL_INCLUDE_RE.findall(preamble):
        dependency = resolve_local_include(path, include)
        if dependency is not None:
            hash_local_include(dependency, digest, set())
    return digest.hexdigest()


def merged_source_path(row: dict[str, str]) -> Path:
    reference = (row["reference_file"] or row["object_source"]).replace("\\", "/")
    if re.match(r"^[A-Za-z]:/", reference):
        reference = reference[3:]
    relative = PurePosixPath(reference)
    if not reference or relative.is_absolute() or ".." in relative.parts:
        raise RuntimeError(
            f"Function has no safe reference path: {row['address']} "
            f"{row['raw_name']}"
        )
    override = IMPLEMENTATION_OVERRIDES.get(relative.as_posix())
    if override is not None:
        relative = PurePosixPath(override)
    return SOURCE_ROOT.joinpath(*relative.parts)


def discover_function_sources() -> dict[int, FunctionSource]:
    if not SOURCE_ROOT.exists():
        return {}

    sources: dict[int, FunctionSource] = {}
    for path in SOURCE_ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in SOURCE_SUFFIXES:
            continue

        legacy = re.fullmatch(r"[0-9A-Fa-f]{8}", path.stem)
        if legacy is not None:
            address = int(path.stem, 16)
            if address in sources:
                raise RuntimeError(f"Duplicate source for 0x{address:08X}")
            validate_instruction_asm(address, path.read_text(encoding="utf-8"))
            sources[address] = FunctionSource(address, path, False)
            continue

        text = path.read_text(encoding="utf-8")
        matches = list(MARKER_RE.finditer(text))
        guarded = True
        if not matches:
            matches = list(ADDRESS_MARKER_RE.finditer(text))
            guarded = False
        for index, match in enumerate(matches):
            address = int(match.group(1), 16)
            if address in sources:
                raise RuntimeError(f"Duplicate source for 0x{address:08X}")
            end = (
                matches[index + 1].start()
                if index + 1 < len(matches)
                else len(text)
            )
            validate_instruction_asm(address, text[match.start():end])
            sources[address] = FunctionSource(
                address,
                path,
                True,
                guarded,
            )
    return sources


def function_block(row: dict[str, str], source: str) -> str:
    address = int(row["address"], 0)
    validate_instruction_asm(address, source)
    source = normalize_matching_annotations(source)
    return (
        f"// {row['address']} {row['raw_name']}\n"
        f"{source.rstrip()}\n"
    )


def install_function_source(row: dict[str, str], source: str) -> Path:
    address = int(row["address"], 0)
    path = merged_source_path(row)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if (
        selector_macro(address) in existing
        or re.search(
            rf"^// 0x{address:08X}\s+",
            existing,
            re.MULTILINE,
        )
    ):
        raise RuntimeError(f"Source already exists for {row['address']}")
    if MARKER_RE.search(existing):
        raise RuntimeError(
            f"{path.relative_to(ROOT)} still uses selector guards; "
            "migrate it before adding another function"
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    prefix = existing.rstrip()
    if not prefix:
        prefix = (
            "// Matching decompilation functions extracted by generated "
            "build shims.\n"
        )
    path.write_text(
        prefix + "\n\n" + function_block(row, source),
        encoding="utf-8",
    )
    return path


def write_selector_shim(source: FunctionSource) -> Path:
    suffix = ".c" if source.path.suffix.lower() == ".c" else ".cpp"
    shim = GENERATED_SOURCE_ROOT / f"{source.address:08X}{suffix}"
    shim.parent.mkdir(parents=True, exist_ok=True)
    include_path = source.path.relative_to(ROOT).as_posix()
    lines = []
    if source.merged and source.guarded:
        lines.append(f"#define {selector_macro(source.address)} 1")
        text = source.path.read_text(encoding="utf-8")
        marker = f"#if defined({selector_macro(source.address)})"
        start = text.index(marker)
        following = MARKER_RE.search(text, start + len(marker))
        end = following.start() if following else len(text)
        block = text[start:end].rstrip().encode()
        lines.append(
            f"// source-block-sha1: {hashlib.sha1(block).hexdigest()}"
        )
        lines.append(
            f"// shared-context-sha1: "
            f"{shared_context_digest(source.path, text)}"
        )
        lines.append('#include "decomp_annotations.h"')
        lines.append(f'#include "{include_path}"')
    elif source.merged:
        text = source.path.read_text(encoding="utf-8")
        matches = list(ADDRESS_MARKER_RE.finditer(text))
        selected_index = next(
            index
            for index, match in enumerate(matches)
            if int(match.group(1), 16) == source.address
        )
        match = matches[selected_index]
        end = (
            matches[selected_index + 1].start()
            if selected_index + 1 < len(matches)
            else len(text)
        )
        block = text[match.start():end].rstrip()
        preamble = text[: matches[0].start()].rstrip()
        marker_line = text[: match.start()].count("\n") + 1
        lines.append(
            f"// source-block-sha1: "
            f"{hashlib.sha1(block.encode()).hexdigest()}"
        )
        lines.append(
            f"// shared-context-sha1: "
            f"{shared_context_digest(source.path, text)}"
        )
        lines.append(
            f'#line {marker_line} '
            f'"{source.path.relative_to(ROOT).as_posix()}"'
        )
        lines.append('#include "decomp_annotations.h"')
        if preamble:
            lines.append(preamble)
        lines.append(block)
    else:
        digest = hashlib.sha1(source.path.read_bytes()).hexdigest()
        lines.append(f"// source-file-sha1: {digest}")
        lines.append('#include "decomp_annotations.h"')
        lines.append(f'#include "{include_path}"')
    content = "\n".join(lines) + "\n"
    if not shim.exists() or shim.read_text(encoding="utf-8") != content:
        shim.write_text(content, encoding="utf-8")
    return shim
